name             'cog_c7common'
maintainer       'Lauri Jesmin'
maintainer_email 'lauri.jesmin@cashongo.co.uk'
license          'all_rights'
description      'Installs/Configures Centos 7 utilities'
long_description 'Installs/Configures Centos 7 utilities'
version          '0.1.8'
